shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*

overrides:
  "@types/node@22>undici-types": ^6.25.0

catalog:
  "@antfu/eslint-config": ^7.2.0
  "@changesets/cli": ^2.29.8
  "@commitlint/cli": ^20.3.1
  "@commitlint/config-conventional": ^20.3.1
  "@commitlint/types": ^20.3.1
  "@eslint/compat": ^2.0.1
  "@total-typescript/ts-reset": ^0.6.1
  "@tsconfig/node-lts": ^24.0.0
  "@tsconfig/node-ts": ^23.6.4
  "@tsconfig/node24": ^24.0.4
  "@tsconfig/strictest": ^2.0.8
  "@tsconfig/vite-react": ^7.0.2
  "@types/lint-staged": ^14.0.0
  "@types/node": ^25.6.0
  "@typescript/native-preview": ^7.0.0-dev.20260421.2
  "@vp-tw/eslint-config": ^0.2.0
  commitizen: ^4.3.1
  cspell: ^9.6.2
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-mdx: ^3.6.2
  eslint-plugin-package-json: ^0.88.2
  eslint-plugin-prettier: ^5.5.5
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  npm-run-all2: ^8.0.4
  oxfmt: ^0.27.0
  pathe: ^2.0.3
  typescript: ^6.0.3

onlyBuiltDependencies:
  - unrs-resolver
